import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Providers from './providers'; // 기존 Providers 컴포넌트 가져오기
import { ModalProvider } from '@/components/modal/ModalContext';
import CustomModal from '@/components/modal/CustomModal';
import '../styles/globals.scss';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <Providers>
          <ModalProvider>
            {children}
            <CustomModal />
          </ModalProvider>
        </Providers>
      </body>
    </html>
  );
}
